-- Autodeploy is a fact about a place, so it is no longer a fact about a project.
--
-- The column said that a push or a tag starts no run at all for this project. That is
-- not a fact about deployments — it also stopped the build, which is nothing to do with
-- where anything is deployed to — and it could not be said about one place rather than
-- another, which is the question everybody actually has when a project goes to two
-- clusters.
--
-- The switch now lives on each row a deployment module declares, as a flag the module
-- names, and it is resolved the way `enabled` is: the most specific level that said
-- anything about it decides. Absent everywhere means on, because nothing is stopped
-- unless somebody stopped it.
--
-- The row's other switch is untouched and still the coarser question — whether this
-- project may deploy here at all. Turning that one off removes the place; turning this
-- one off leaves it, and leaves it running for whoever else has it.
ALTER TABLE projects DROP COLUMN IF EXISTS auto_deploy_paused;