-- What a running deployment last said, kept where a page opened halfway through can find it.
--
-- A deployment narrates itself line by line, the core relays each line as it arrives, and the
-- lines are appended to the job's log. That is everything a page needs — except that a page
-- opened halfway through saw none of them.
--
-- So the page is left with the plan and nothing to put under it: the steps are known in advance
-- and none of them are marked, because every mark comes from a line that was said before the
-- page existed. A reader opening a deployment in progress is shown a list of seven steps in the
-- colour of steps not yet reached, which is a claim about a deployment that has not started.
--
-- The text of the log cannot answer it. A line is `out| <ms>| <what the module said>`, and
-- taking "3 of 4" out of a sentence is taking a number out of prose — somebody has to keep that
-- prose and those numbers in step, and they are written by two different people for two different
-- readers. So the fields are kept as fields, next to the row that says which operation this is.
--
-- One row per job, holding the most recent line's fields. Not the history of them: the history
-- is in the log, which is what a reader opens when they want the account, and this exists only so
-- that a page arriving late can say where the operation is rather than where it started.
--
-- Nullable and never backfilled. The deployments that already ran are over, and writing a
-- progress for a job that finished yesterday would be a claim about it that nobody observed.
ALTER TABLE jobs ADD COLUMN deploy_progress JSONB;
