{{- if not .Values.app.existingSecret -}}
{{- $name := include "dogit.appSecretName" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
{{- $key := randBytes 32 -}}
{{- if and $existing (hasKey $existing.data .Values.app.secretKeyKey) -}}
{{- $key = index $existing.data .Values.app.secretKeyKey | b64dec -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "dogit.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.app.secretKeyKey }}: {{ $key | quote }}
{{- end }}
{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
{{- $name := include "dogit.postgresqlSecretName" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
{{- $password := randAlphaNum 40 -}}
{{- if and $existing (hasKey $existing.data .Values.postgresql.auth.passwordKey) -}}
{{- $password = index $existing.data .Values.postgresql.auth.passwordKey | b64dec -}}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "dogit.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgresql.auth.passwordKey }}: {{ $password | quote }}
{{- end }}
